# Generated by Django 3.0.5 on 2020-06-01 21:19

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Enter a name for the exercise (e.g. Bench Press). Do not include type, such as Dumbbell or Barbell.', max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='WorkoutInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('d1ecab06-ef28-4784-8009-f112cb67c972'), help_text='Unique ID for a particular workout.', primary_key=True, serialize=False)),
                ('date_performed', models.DateField(default=django.utils.timezone.now)),
                ('exercise', models.ManyToManyField(to='fitness.Exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ExerciseInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('0620bc0f-84b6-46cf-99b1-2d4abc4a3198'), help_text='Unique ID for a particular exercise instance.', primary_key=True, serialize=False)),
                ('date_performed', models.DateField(default=django.utils.timezone.now)),
                ('sets', models.PositiveSmallIntegerField(default=0)),
                ('reps', models.PositiveSmallIntegerField(default=0)),
                ('weight', models.PositiveIntegerField(default=0, help_text='Enter the weight of each dumbbell or the whole barbell')),
                ('type', models.CharField(choices=[('db', 'Dumbbell'), ('bb', 'Barbell'), ('bw', 'Bodyweight')], default='db', help_text='Enter "db", "bb" or "bw"', max_length=15)),
                ('name', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='fitness.Exercise')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['date_performed', 'name'],
            },
        ),
    ]
