# Generated by Django 3.0.5 on 2020-06-01 21:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='exercise',
            options={'ordering': ['name']},
        ),
        migrations.AlterField(
            model_name='exerciseinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('b8b067a4-3e70-4099-8d68-b8ed49dcfe15'), help_text='Unique ID for a particular exercise instance.', primary_key=True, serialize=False),
        ),
        migrations.DeleteModel(
            name='WorkoutInstance',
        ),
    ]
