# Generated by Django 3.0.5 on 2020-06-01 21:44

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('fitness', '0002_auto_20200601_1643'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseinstance',
            name='id',
            field=models.UUIDField(default=uuid.UUID('7bdf669e-2b6e-48c0-b41d-9374cc90519c'), help_text='Unique ID for a particular exercise instance.', primary_key=True, serialize=False),
        ),
        migrations.CreateModel(
            name='WorkoutInstance',
            fields=[
                ('id', models.UUIDField(default=uuid.UUID('62ed8f07-91bb-4950-b9e1-8c61c1b51a48'), help_text='Unique ID for a particular workout.', primary_key=True, serialize=False)),
                ('date_performed', models.DateField(default=django.utils.timezone.now)),
                ('exercise', models.ManyToManyField(to='fitness.ExerciseInstance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
