# Generated by Django 3.0.5 on 2020-06-18 03:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fitness', '0005_auto_20200602_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exerciseinstance',
            name='weight',
            field=models.DecimalField(decimal_places=1, default=0, help_text='Enter the weight of each dumbbell or the whole barbell', max_digits=5),
        ),
    ]
